# -*- coding: utf-8 -*-
"""model_testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1md93J01GOj8wrq4iMBZ6sKx-TuAMzGp7
"""

from sklearn.metrics import mean_squared_error
import numpy as np

# Загрузка тестовых данных
test_data = np.load("test/test_data.npy")

# Загрузка обученной модели (если есть)
model = load_model("trained_model.joblib")

# Предсказание на тестовых данных
predictions = model.predict(test_data)

# Пример вычисления MSE
mse = mean_squared_error(true_values, predictions)