# -*- coding: utf-8 -*-
"""model_preparation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1md93J01GOj8wrq4iMBZ6sKx-TuAMzGp7
"""

from sklearn.linear_model import LinearRegression
import numpy as np

# Загрузка предобработанных данных
train_data_scaled = np.load("train/train_data_scaled.npy")

# Создание и обучение модели
model = LinearRegression()
model.fit(train_data_scaled[:, :-1], train_data_scaled[:, -1])

# Сохранение модели
model.save("trained_model.joblib")